spring:
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:devdb;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password: changeme
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
rest:
  connectTimeout: 5000
  readTimeout: 5000

retry:
  maxAttempts: 3
  retryDelay: 500

app:
  schedule:
    poolSize: 3
    updateMatchFixedRate: '180000'
    dumpJobFixedRate: '5000'
  job:
    poolSize: 8
    queueSize: 100
    minDelay: 200
    maxDelay: 500
  match:
    baseUrl: 'https://m.nowscore.com'

    matchListPath: '/results.htm?date=<date>'

    handicapPath: '/Handicap/<matchId>.htm'
    handicapDetailPath: '/HandicapDetail/<matchId>_<providerId>.htm'

    oddsPath: '/1x2/<matchId>.htm'
    oddsDetailPath: '/1x2Detail/<matchId>_<providerId>.htm'

    overUnderPath: '/OverUnder/<matchId>.htm'
    overUnderDetailPath: '/OuDetail/<matchId>_<providerId>.htm'

    hotLeagues:
      - id: 36
        name: '英超'
      - id: 37
        name: '英冠'
      - id: 31
        name: '西甲'
      - id: 8
        name: '德甲'
      - id: 9
        name: '德乙'
      - id: 34
        name: '意甲'
      - id: 11
        name: '法甲'
      - id: 25
        name: '日职联'
      - id: 284
        name: '日职乙'
      - id: 15
        name: '韩K联'
      - id: 273
        name: '澳洲甲'
      - id: 23
        name: '葡超'
      - id: 22
        name: '挪超'
      - id: 16
        name: '荷甲'
      - id: 5
        name: '比甲'
      - id: 26
        name: '瑞超'
      - id: 10
        name: '俄超'
      - id: 29
        name: '苏超'
      - id: 60
        name: '中超'
      - id: 61
        name: '中甲'
      - id: 650
        name: '世欧预'
      - id: 648
        name: '世亚预'
      - id: 652
        name: '世南美预'
      - id: 75
        name: '世界杯'
      - id: 67
        name: '欧洲杯'
      - id: 1864
        name: '欧国联'
      - id: 103
        name: '欧冠杯'
      - id: 113
        name: '欧联杯'
      - id: 192
        name: '亚冠杯'
      - id: 89
        name: '自由杯'
      - id: 109
        name: '超霸杯'
      - id: 344
        name: '美冠杯'

    handicapProviders:
      - id: 1
        name: '澳门'
      - id: 3
        name: 'Crown'
      - id: 8
        name: '365'
      - id: 9
        name: '威廉希尔'
      - id: 12
        name: '易胜博'
      - id: 14
        name: '伟德'

    oddsProviders:
      - id: 80
        name: '澳门'
      - id: 545
        name: 'Crown'
      - id: 281
        name: '365'
      - id: 115
        name: '威廉希尔'
      - id: 81
        name: '易胜博'
      - id: 90
        name: '伟德'
      - id: 82
        name: '立博'

    overUnderProviders:
      - id: 1
        name: '澳门'
      - id: 3
        name: 'Crown'
      - id: 8
        name: '365'
      - id: 9
        name: '威廉希尔'
      - id: 12
        name: '易胜博'
      - id: 14
        name: '伟德'
      - id: 4
        name: '立博'
