spring:
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:devdb;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password: changeme
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

app:
  schedule:
    fixedRate: '18000'
  match:
    baseUrl: 'https://m.nowscore.com'
    matchListPath: '/results.htm?date=<date>'
    handicapPath: '/Handicap/<matchId>.htm'
    handicapDetailPath: '/HandicapDetail/<matchId>_<providerId>.htm'
    overUnderDetailPath: '/OuDetail/<matchId>_<providerId>.htm'
    oddsPath: '/1x2/<placeholder>.htm'
    oddsDetailPath: '/1x2Detail/<matchId>_<providerId>.htm'
    handicapProviders:
      - id: 9
        name: '威廉希尔'
      - id: 1
        name: '澳门'
    oddsProviders:
      - id: 115
        name: '威廉希尔'
      - id: 80
        name: '澳门'
