spring:
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:devdb;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password: changeme
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
rest:
  connectTimeout: 5000
  readTimeout: 5000

retry:
  maxAttempts: 3
  maxDelay: 200

app:
  schedule:
    fixedRate: '5000'
  match:
    baseUrl: 'https://m.nowscore.com'

    matchListPath: '/results.htm?date=<date>'

    handicapPath: '/Handicap/<matchId>.htm'
    handicapDetailPath: '/HandicapDetail/<matchId>_<providerId>.htm'

    oddsPath: '/1x2/<matchId>.htm'
    oddsDetailPath: '/1x2Detail/<matchId>_<providerId>.htm'

    overUnderPath: '/OverUnder/<matchId>.htm'
    overUnderDetailPath: '/OuDetail/<matchId>_<providerId>.htm'

    handicapProviders:
      - id: 1
        name: '澳门'
      - id: 3
        name: 'Crown'
      - id: 8
        name: '365'
      - id: 9
        name: '威廉希尔'
      - id: 12
        name: '易胜博'
      - id: 14
        name: '伟德'

    oddsProviders:
      - id: 80
        name: '澳门'
      - id: 545
        name: 'Crown'
      - id: 281
        name: '365'
      - id: 115
        name: '威廉希尔'
      - id: 81
        name: '易胜博'
      - id: 90
        name: '伟德'
      - id: 82
        name: '立博'

    overUnderProviders:
      - id: 1
        name: '澳门'
      - id: 3
        name: 'Crown'
      - id: 8
        name: '365'
      - id: 9
        name: '威廉希尔'
      - id: 12
        name: '易胜博'
      - id: 14
        name: '伟德'
      - id: 4
        name: '立博'
